### PR TITLE
Add Frontend API

### PR DESCRIPTION
**Pull request by Beaux44**

### CODE REVIEW

**Comment by rogueyoshi** [comment]
Ty for this

**Comment by bennetthardwick** [comment]
Looks good to me I just pushed to your branch to get CI passing. I haven't tested but will play around with it this weekend. Thanks!

**Comment by Beaux44** [comment]
Unfortunately I don't have a Mac to test with, so I'm not sure what needs to be changed for the Mac build, but I did get it to successfully link with my project on both Windows and Linux.

**Comment by bennetthardwick** [comment]
> Unfortunately I don't have a Mac to test with, so I'm not sure what needs to be changed for the Mac build, but I did get it to successfully link with my project on both Windows and Linux.

No problem! I have a Mac laying around somewhere so I'll try and _finally_ get it to work on there + Github actions this weekend.

**Pull request merged**
