### PR TITLE
Fix type mismatch of raw_audio2

### LINKED ISSUE #28: Fails to build Rust OBS Wrapper
The current master branch fails to build Rust OBS Wrapper.

```shell
$ git log | head -1
commit 08d66c684307bc804c9421ef2b0b4b963ceb4f4c

$ cargo build
(snip warnings)
   --> src\output\mod.rs:88:45
    |
88  |                       self.info.[<$f>] = Some(ffi::[<$f>]::<D>);
    |                                          ---- ^^^^^^^^^^^^^^^^ expected `u32`, found `u64`
    |                                          |
    |                                          arguments to this enum variant are incorrect
...
96  | / impl_output_builder! {
97  | |     get_name => GetNameOutput
98  | |     // this two is required
99  | |     // start => StartOutput
...   |
117 | |     get_connect_time_ms => GetConnectTimeMsOutput
118 | | }
    | |_- in this macro invocation
    |
    = note: expected fn pointer `unsafe extern "C" fn(_, u32, _)`
                  found fn item `unsafe extern "C" fn(_, u64, _) {raw_audio2::<D>}`
note: tuple variant defined here
    = note: this error originates in the macro `impl_output_builder` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0308`.
error: could not compile `obs-wrapper` due to previous error
```

My build environment is here:

```
$ cargo -V
cargo 1.63.0 (fd9c4297c 2022-07-01)
$ rustc -V
rustc 1.63.0 (4b91a6ea7 2022-08-08)
$ rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\y\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

### PR DESCRIPTION
**Pull request by yoshinorisano**
This pull request fix #28.

### CODE REVIEW

**Comment by yoshinorisano** [comment]
In the obs-sys/generated/bindings.rs, the interface of ``` raw_audio2 ``` is defiend like this:

```rust
obs_output_infopub struct  {
(snip)
    pub raw_audio2: ::std::option::Option<
        unsafe extern "C" fn(
            data: *mut ::std::os::raw::c_void,
            idx: size_t,
            frames: *mut audio_data,
        ),
    >,
}
```

And also ``` size_t ``` (raw_audio2's 2nd argument type) is defined like this:

```rust
pub type size_t = ::std::os::raw::c_ulong;
```

So I used ``` ::std::os::raw::c_ulong ``` to match the type.

**Comment by yoshinorisano** [comment]
@bennetthardwick 
Could you review this pull request?

**Comment by bennetthardwick** [comment]
Thanks for the fix @yoshinorisano I should probably look into testing against 32 bit operating systems. I've put out `0.3.1` with your changes 👍🏻

**Comment by yoshinorisano** [comment]
@bennetthardwick 
Thank you!

**Pull request merged**
