### PR TITLE
[WIP] Add APIs for obs_data_set_default_xxx()

### PR DESCRIPTION
**Pull request by yoshinorisano**
I'm currently developping a plugin using rust-obs-plugin.
I found that there are no APIs for ``` obs_data_set_default_xxx() ```.
So, I tried to add these APIs.
I think that my added APIs are somewhat weird interfaces, so I’d like to make it more sphisticated!

I wrote experimental code for this PR.
https://github.com/yoshinorisano/obs-biquad-filter-plugin/commit/89f830e138cd7f017d246414c1106eb5cb7820db

### CODE REVIEW

**Comment by yoshinorisano** [comment]
@bennetthardwick 
Hi!
Could you review this pull request?

**Comment by yoshinorisano** [comment]
Sorry…
I didn’t notice this PR before I made my PR.
https://github.com/bennetthardwick/rust-obs-plugins/pull/15

**Comment by bennetthardwick** [comment]
Hi @yoshinorisano I just merged PR #31 which included the changes from #15 - can you let me know whether that solves the issue for you?

**Comment by yoshinorisano** [comment]
@bennetthardwick 
Thank you so much!
The issue is solved by your PR.
So, close this PR!

**Pull request closed without merging**
